# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protobufs/auth.proto, protobufs/enums.proto
# plugin: python-betterproto2
# This file has been @generated

# Processed by generate_protos.py: removed 'message_pool', formatted.

__all__ = (
    "CAuthenticationAccessTokenGenerateForAppRequest",
    "CAuthenticationAccessTokenGenerateForAppResponse",
    "CAuthenticationAllowedConfirmation",
    "CAuthenticationBeginAuthSessionViaCredentialsRequest",
    "CAuthenticationBeginAuthSessionViaCredentialsResponse",
    "CAuthenticationBeginAuthSessionViaQrRequest",
    "CAuthenticationBeginAuthSessionViaQrResponse",
    "CAuthenticationDeviceDetails",
    "CAuthenticationGetAuthSessionInfoRequest",
    "CAuthenticationGetAuthSessionInfoResponse",
    "CAuthenticationGetPasswordRsaPublicKeyRequest",
    "CAuthenticationGetPasswordRsaPublicKeyResponse",
    "CAuthenticationPollAuthSessionStatusRequest",
    "CAuthenticationPollAuthSessionStatusResponse",
    "CAuthenticationRefreshTokenRevokeRequest",
    "CAuthenticationTokenRevokeRequest",
    "CAuthenticationUpdateAuthSessionWithMobileConfirmationRequest",
    "CAuthenticationUpdateAuthSessionWithSteamGuardCodeRequest",
    "CAuthenticationUpdateAuthSessionWithSteamGuardCodeResponse",
    "EAuthSessionGuardType",
    "EAuthSessionSecurityHistory",
    "EAuthTokenAppType",
    "EAuthTokenPlatformType",
    "EAuthTokenRevokeAction",
    "ESessionPersistence",
    "ETokenRenewalType",
)
from dataclasses import dataclass

import betterproto2

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class EAuthSessionGuardType(betterproto2.Enum):
    k_EAuthSessionGuardType_Unknown = 0
    k_EAuthSessionGuardType_None = 1
    k_EAuthSessionGuardType_EmailCode = 2
    k_EAuthSessionGuardType_DeviceCode = 3
    k_EAuthSessionGuardType_DeviceConfirmation = 4
    k_EAuthSessionGuardType_EmailConfirmation = 5
    k_EAuthSessionGuardType_MachineToken = 6
    k_EAuthSessionGuardType_LegacyMachineAuth = 7


class EAuthSessionSecurityHistory(betterproto2.Enum):
    k_EAuthSessionSecurityHistory_Invalid = 0
    k_EAuthSessionSecurityHistory_UsedPreviously = 1
    k_EAuthSessionSecurityHistory_NoPriorHistory = 2


class EAuthTokenAppType(betterproto2.Enum):
    k_EAuthTokenAppType_Unknown = 0
    k_EAuthTokenAppType_Mobile_SteamApp = 1
    k_EAuthTokenAppType_Mobile_ChatApp = 2


class EAuthTokenPlatformType(betterproto2.Enum):
    k_EAuthTokenPlatformType_Unknown = 0
    k_EAuthTokenPlatformType_SteamClient = 1
    k_EAuthTokenPlatformType_WebBrowser = 2
    k_EAuthTokenPlatformType_MobileApp = 3


class EAuthTokenRevokeAction(betterproto2.Enum):
    k_EAuthTokenRevokeLogout = 0
    k_EAuthTokenRevokePermanent = 1
    k_EAuthTokenRevokeReplaced = 2
    k_EAuthTokenRevokeSupport = 3
    k_EAuthTokenRevokeConsume = 4
    k_EAuthTokenRevokeNonRememberedLogout = 5
    k_EAuthTokenRevokeNonRememberedPermanent = 6
    k_EAuthTokenRevokeAutomatic = 7


class ESessionPersistence(betterproto2.Enum):
    k_ESessionPersistence_Invalid = -1
    k_ESessionPersistence_Ephemeral = 0
    k_ESessionPersistence_Persistent = 1


class ETokenRenewalType(betterproto2.Enum):
    """
    CAuthentication_UpdateAuthSessionWithMobileConfirmation_Response {}
    """

    k_ETokenRenewalType_None = 0
    k_ETokenRenewalType_Allow = 1


@dataclass(eq=False, repr=False)
class CAuthenticationAccessTokenGenerateForAppRequest(betterproto2.Message):
    refresh_token: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    steamid: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    renewal_type: "ETokenRenewalType" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, default_factory=lambda: ETokenRenewalType(0)
    )


@dataclass(eq=False, repr=False)
class CAuthenticationAccessTokenGenerateForAppResponse(betterproto2.Message):
    access_token: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    refresh_token: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CAuthenticationAllowedConfirmation(betterproto2.Message):
    confirmation_type: "EAuthSessionGuardType" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthSessionGuardType(0)
    )
    associated_message: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CAuthenticationBeginAuthSessionViaCredentialsRequest(betterproto2.Message):
    device_friendly_name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    account_name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    encrypted_password: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    encryption_timestamp: "int" = betterproto2.field(4, betterproto2.TYPE_UINT64)
    remember_login: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)
    platform_type: "EAuthTokenPlatformType" = betterproto2.field(
        6, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenPlatformType(0)
    )
    persistence: "ESessionPersistence" = betterproto2.field(
        7, betterproto2.TYPE_ENUM, default_factory=lambda: ESessionPersistence(0)
    )
    website_id: "str" = betterproto2.field(8, betterproto2.TYPE_STRING)
    device_details: "CAuthenticationDeviceDetails | None" = betterproto2.field(
        9, betterproto2.TYPE_MESSAGE, optional=True
    )
    guard_data: "str" = betterproto2.field(10, betterproto2.TYPE_STRING)
    language: "int" = betterproto2.field(11, betterproto2.TYPE_UINT32)
    qos_level: "int" = betterproto2.field(12, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False)
class CAuthenticationBeginAuthSessionViaCredentialsResponse(betterproto2.Message):
    client_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    request_id: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)
    interval: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)
    allowed_confirmations: "list[CAuthenticationAllowedConfirmation]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )
    steamid: "int" = betterproto2.field(5, betterproto2.TYPE_UINT64)
    weak_token: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)
    agreement_session_url: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    extended_error_message: "str" = betterproto2.field(8, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CAuthenticationBeginAuthSessionViaQrRequest(betterproto2.Message):
    device_friendly_name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    platform_type: "EAuthTokenPlatformType" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenPlatformType(0)
    )
    device_details: "CAuthenticationDeviceDetails | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )
    website_id: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CAuthenticationBeginAuthSessionViaQrResponse(betterproto2.Message):
    client_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    challenge_url: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    request_id: "bytes" = betterproto2.field(3, betterproto2.TYPE_BYTES)
    interval: "float" = betterproto2.field(4, betterproto2.TYPE_FLOAT)
    allowed_confirmations: "list[CAuthenticationAllowedConfirmation]" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, repeated=True
    )
    version: "int" = betterproto2.field(6, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False)
class CAuthenticationDeviceDetails(betterproto2.Message):
    device_friendly_name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    platform_type: "EAuthTokenPlatformType" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenPlatformType(0)
    )
    os_type: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)
    gaming_device_type: "int" = betterproto2.field(4, betterproto2.TYPE_UINT32)
    client_count: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)
    machine_id: "bytes" = betterproto2.field(6, betterproto2.TYPE_BYTES)
    app_type: "EAuthTokenAppType" = betterproto2.field(
        7, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenAppType(0)
    )


@dataclass(eq=False, repr=False)
class CAuthenticationGetAuthSessionInfoRequest(betterproto2.Message):
    client_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)


@dataclass(eq=False, repr=False)
class CAuthenticationGetAuthSessionInfoResponse(betterproto2.Message):
    ip: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    geoloc: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    city: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    state: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    country: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)
    platform_type: "EAuthTokenPlatformType" = betterproto2.field(
        6, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenPlatformType(0)
    )
    device_friendly_name: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    version: "int" = betterproto2.field(8, betterproto2.TYPE_INT32)
    login_history: "EAuthSessionSecurityHistory" = betterproto2.field(
        9, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthSessionSecurityHistory(0)
    )
    requestor_location_mismatch: "bool" = betterproto2.field(10, betterproto2.TYPE_BOOL)
    high_usage_login: "bool" = betterproto2.field(11, betterproto2.TYPE_BOOL)
    requested_persistence: "ESessionPersistence" = betterproto2.field(
        12, betterproto2.TYPE_ENUM, default_factory=lambda: ESessionPersistence(0)
    )
    device_trust: "int" = betterproto2.field(13, betterproto2.TYPE_INT32)
    app_type: "EAuthTokenAppType" = betterproto2.field(
        14, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenAppType(0)
    )


@dataclass(eq=False, repr=False)
class CAuthenticationGetPasswordRsaPublicKeyRequest(betterproto2.Message):
    account_name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CAuthenticationGetPasswordRsaPublicKeyResponse(betterproto2.Message):
    publickey_mod: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    publickey_exp: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    timestamp: "int" = betterproto2.field(3, betterproto2.TYPE_UINT64)


@dataclass(eq=False, repr=False)
class CAuthenticationPollAuthSessionStatusRequest(betterproto2.Message):
    client_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    request_id: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)
    token_to_revoke: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)


@dataclass(eq=False, repr=False)
class CAuthenticationPollAuthSessionStatusResponse(betterproto2.Message):
    new_client_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    new_challenge_url: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    refresh_token: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    access_token: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    had_remote_interaction: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)
    account_name: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)
    new_guard_data: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    agreement_session_url: "str" = betterproto2.field(8, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CAuthenticationRefreshTokenRevokeRequest(betterproto2.Message):
    """
    message CAuthentication_Token_Revoke_Response {}
    """

    token_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    steamid: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    revoke_action: "EAuthTokenRevokeAction" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenRevokeAction(0)
    )
    signature: "bytes" = betterproto2.field(4, betterproto2.TYPE_BYTES)


@dataclass(eq=False, repr=False)
class CAuthenticationTokenRevokeRequest(betterproto2.Message):
    token: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    revoke_action: "EAuthTokenRevokeAction" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenRevokeAction(0)
    )


@dataclass(eq=False, repr=False)
class CAuthenticationUpdateAuthSessionWithMobileConfirmationRequest(betterproto2.Message):
    version: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)
    client_id: "int" = betterproto2.field(2, betterproto2.TYPE_UINT64)
    steamid: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)
    signature: "bytes" = betterproto2.field(4, betterproto2.TYPE_BYTES)
    confirm: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)
    persistence: "ESessionPersistence" = betterproto2.field(
        6, betterproto2.TYPE_ENUM, default_factory=lambda: ESessionPersistence(0)
    )


@dataclass(eq=False, repr=False)
class CAuthenticationUpdateAuthSessionWithSteamGuardCodeRequest(betterproto2.Message):
    client_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    steamid: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    code: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    code_type: "EAuthSessionGuardType" = betterproto2.field(
        4, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthSessionGuardType(0)
    )


@dataclass(eq=False, repr=False)
class CAuthenticationUpdateAuthSessionWithSteamGuardCodeResponse(betterproto2.Message):
    agreement_session_url: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
