# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protobufs/auth.proto, protobufs/base.proto, protobufs/enums.proto, protobufs/phone.proto, protobufs/twofactor.proto
# plugin: python-betterproto2
# This file has been @generated

# Processed by generate_protos.py: removed 'message_pool', formatted.

__all__ = (
    "CAuthenticationAccessTokenGenerateForAppRequest",
    "CAuthenticationAccessTokenGenerateForAppResponse",
    "CAuthenticationAllowedConfirmation",
    "CAuthenticationBeginAuthSessionViaCredentialsRequest",
    "CAuthenticationBeginAuthSessionViaCredentialsResponse",
    "CAuthenticationBeginAuthSessionViaQrRequest",
    "CAuthenticationBeginAuthSessionViaQrResponse",
    "CAuthenticationDeviceDetails",
    "CAuthenticationGetAuthSessionInfoRequest",
    "CAuthenticationGetAuthSessionInfoResponse",
    "CAuthenticationGetAuthSessionsForAccountResponse",
    "CAuthenticationGetPasswordRsaPublicKeyRequest",
    "CAuthenticationGetPasswordRsaPublicKeyResponse",
    "CAuthenticationPollAuthSessionStatusRequest",
    "CAuthenticationPollAuthSessionStatusResponse",
    "CAuthenticationRefreshTokenEnumerateRequest",
    "CAuthenticationRefreshTokenEnumerateResponse",
    "CAuthenticationRefreshTokenEnumerateResponseRefreshTokenDescription",
    "CAuthenticationRefreshTokenEnumerateResponseTokenUsageEvent",
    "CAuthenticationRefreshTokenRevokeRequest",
    "CAuthenticationTokenRevokeRequest",
    "CAuthenticationUpdateAuthSessionWithMobileConfirmationRequest",
    "CAuthenticationUpdateAuthSessionWithSteamGuardCodeRequest",
    "CAuthenticationUpdateAuthSessionWithSteamGuardCodeResponse",
    "CMsgIpAddress",
    "CPhoneAccountPhoneStatusResponse",
    "CPhoneAddPhoneToAccountResponse",
    "CPhoneConfirmAddPhoneToAccountRequest",
    "CPhoneIsAccountWaitingForEmailConfirmationResponse",
    "CPhoneSendPhoneVerificationCodeRequest",
    "CPhoneSetAccountPhoneNumberRequest",
    "CPhoneSetAccountPhoneNumberResponse",
    "CPhoneVerifyAccountPhoneWithCodeRequest",
    "CRemoveAuthenticatorViaChallengeContinueReplacementToken",
    "CTwoFactorAddAuthenticatorRequest",
    "CTwoFactorAddAuthenticatorResponse",
    "CTwoFactorFinalizeAddAuthenticatorRequest",
    "CTwoFactorFinalizeAddAuthenticatorResponse",
    "CTwoFactorRemoveAuthenticatorRequest",
    "CTwoFactorRemoveAuthenticatorResponse",
    "CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest",
    "CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse",
    "CTwoFactorRemoveAuthenticatorViaChallengeStartResponse",
    "CTwoFactorStatusRequest",
    "CTwoFactorStatusResponse",
    "CTwoFactorTimeRequest",
    "CTwoFactorTimeResponse",
    "CTwoFactorUsageEvent",
    "EAuthSessionGuardType",
    "EAuthSessionSecurityHistory",
    "EAuthTokenAppType",
    "EAuthTokenPlatformType",
    "EAuthTokenRevokeAction",
    "EAuthTokenState",
    "EAuthenticationType",
    "ESessionPersistence",
    "ETokenRenewalType",
    "ETwoFactorStatusFieldFlag",
    "ETwoFactorUsageType",
)
from dataclasses import dataclass

import betterproto2

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class EAuthenticationType(betterproto2.Enum):
    """
    message CAuthentication_RefreshToken_Revoke_Response {}
    """

    k_EAuthenticationType_Unknown = 0
    k_EAuthenticationType_Password = 1
    k_EAuthenticationType_QR = 2
    k_EAuthenticationType_AccountCreation = 3
    k_EAuthenticationType_GuestAccount = 4


class EAuthSessionGuardType(betterproto2.Enum):
    k_EAuthSessionGuardType_Unknown = 0
    k_EAuthSessionGuardType_None = 1
    k_EAuthSessionGuardType_EmailCode = 2
    k_EAuthSessionGuardType_DeviceCode = 3
    k_EAuthSessionGuardType_DeviceConfirmation = 4
    k_EAuthSessionGuardType_EmailConfirmation = 5
    k_EAuthSessionGuardType_MachineToken = 6
    k_EAuthSessionGuardType_LegacyMachineAuth = 7


class EAuthSessionSecurityHistory(betterproto2.Enum):
    k_EAuthSessionSecurityHistory_Invalid = 0
    k_EAuthSessionSecurityHistory_UsedPreviously = 1
    k_EAuthSessionSecurityHistory_NoPriorHistory = 2


class EAuthTokenAppType(betterproto2.Enum):
    k_EAuthTokenAppType_Unknown = 0
    k_EAuthTokenAppType_Mobile_SteamApp = 1
    k_EAuthTokenAppType_Mobile_ChatApp = 2


class EAuthTokenPlatformType(betterproto2.Enum):
    k_EAuthTokenPlatformType_Unknown = 0
    k_EAuthTokenPlatformType_SteamClient = 1
    k_EAuthTokenPlatformType_WebBrowser = 2
    k_EAuthTokenPlatformType_MobileApp = 3


class EAuthTokenRevokeAction(betterproto2.Enum):
    k_EAuthTokenRevokeLogout = 0
    k_EAuthTokenRevokePermanent = 1
    k_EAuthTokenRevokeReplaced = 2
    k_EAuthTokenRevokeSupport = 3
    k_EAuthTokenRevokeConsume = 4
    k_EAuthTokenRevokeNonRememberedLogout = 5
    k_EAuthTokenRevokeNonRememberedPermanent = 6
    k_EAuthTokenRevokeAutomatic = 7


class EAuthTokenState(betterproto2.Enum):
    k_EAuthTokenState_Invalid = 0
    k_EAuthTokenState_New = 1
    k_EAuthTokenState_Confirmed = 2
    k_EAuthTokenState_Issued = 3
    k_EAuthTokenState_Denied = 4
    k_EAuthTokenState_LoggedOut = 5
    k_EAuthTokenState_Consumed = 6
    k_EAuthTokenState_Revoked = 99


class ESessionPersistence(betterproto2.Enum):
    k_ESessionPersistence_Invalid = -1
    k_ESessionPersistence_Ephemeral = 0
    k_ESessionPersistence_Persistent = 1


class ETokenRenewalType(betterproto2.Enum):
    """
    CAuthentication_UpdateAuthSessionWithMobileConfirmation_Response {}
    """

    k_ETokenRenewalType_None = 0
    k_ETokenRenewalType_Allow = 1


class ETwoFactorStatusFieldFlag(betterproto2.Enum):
    k_ETwoFactorStatusFieldFlag_None = 0
    k_ETwoFactorStatusFieldFlag_LastUsage = 1


class ETwoFactorUsageType(betterproto2.Enum):
    k_ETwoFactorUsageType_Unknown = 0
    k_ETwoFactorUsageType_None = 1
    k_ETwoFactorUsageType_MobileConfirmation = 2
    k_ETwoFactorUsageType_Login = 3


@dataclass(eq=False, repr=False)
class CAuthenticationAccessTokenGenerateForAppRequest(betterproto2.Message):
    refresh_token: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    steamid: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    renewal_type: "ETokenRenewalType" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, default_factory=lambda: ETokenRenewalType(0)
    )


@dataclass(eq=False, repr=False)
class CAuthenticationAccessTokenGenerateForAppResponse(betterproto2.Message):
    access_token: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    refresh_token: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CAuthenticationAllowedConfirmation(betterproto2.Message):
    confirmation_type: "EAuthSessionGuardType" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthSessionGuardType(0)
    )
    associated_message: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CAuthenticationBeginAuthSessionViaCredentialsRequest(betterproto2.Message):
    device_friendly_name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    account_name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    encrypted_password: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    encryption_timestamp: "int" = betterproto2.field(4, betterproto2.TYPE_UINT64)
    remember_login: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)
    platform_type: "EAuthTokenPlatformType" = betterproto2.field(
        6, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenPlatformType(0)
    )
    persistence: "ESessionPersistence" = betterproto2.field(
        7, betterproto2.TYPE_ENUM, default_factory=lambda: ESessionPersistence(0)
    )
    website_id: "str" = betterproto2.field(8, betterproto2.TYPE_STRING)
    device_details: "CAuthenticationDeviceDetails | None" = betterproto2.field(
        9, betterproto2.TYPE_MESSAGE, optional=True
    )
    guard_data: "str" = betterproto2.field(10, betterproto2.TYPE_STRING)
    language: "int" = betterproto2.field(11, betterproto2.TYPE_UINT32)
    qos_level: "int" = betterproto2.field(12, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False)
class CAuthenticationBeginAuthSessionViaCredentialsResponse(betterproto2.Message):
    client_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    request_id: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)
    interval: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)
    allowed_confirmations: "list[CAuthenticationAllowedConfirmation]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )
    steamid: "int" = betterproto2.field(5, betterproto2.TYPE_UINT64)
    weak_token: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)
    agreement_session_url: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    extended_error_message: "str" = betterproto2.field(8, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CAuthenticationBeginAuthSessionViaQrRequest(betterproto2.Message):
    device_friendly_name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    platform_type: "EAuthTokenPlatformType" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenPlatformType(0)
    )
    device_details: "CAuthenticationDeviceDetails | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )
    website_id: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CAuthenticationBeginAuthSessionViaQrResponse(betterproto2.Message):
    client_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    challenge_url: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    request_id: "bytes" = betterproto2.field(3, betterproto2.TYPE_BYTES)
    interval: "float" = betterproto2.field(4, betterproto2.TYPE_FLOAT)
    allowed_confirmations: "list[CAuthenticationAllowedConfirmation]" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, repeated=True
    )
    version: "int" = betterproto2.field(6, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False)
class CAuthenticationDeviceDetails(betterproto2.Message):
    device_friendly_name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    platform_type: "EAuthTokenPlatformType" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenPlatformType(0)
    )
    os_type: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)
    gaming_device_type: "int" = betterproto2.field(4, betterproto2.TYPE_UINT32)
    client_count: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)
    machine_id: "bytes" = betterproto2.field(6, betterproto2.TYPE_BYTES)
    app_type: "EAuthTokenAppType" = betterproto2.field(
        7, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenAppType(0)
    )


@dataclass(eq=False, repr=False)
class CAuthenticationGetAuthSessionInfoRequest(betterproto2.Message):
    client_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)


@dataclass(eq=False, repr=False)
class CAuthenticationGetAuthSessionInfoResponse(betterproto2.Message):
    ip: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    geoloc: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    city: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    state: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    country: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)
    platform_type: "EAuthTokenPlatformType" = betterproto2.field(
        6, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenPlatformType(0)
    )
    device_friendly_name: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    version: "int" = betterproto2.field(8, betterproto2.TYPE_INT32)
    login_history: "EAuthSessionSecurityHistory" = betterproto2.field(
        9, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthSessionSecurityHistory(0)
    )
    requestor_location_mismatch: "bool" = betterproto2.field(10, betterproto2.TYPE_BOOL)
    high_usage_login: "bool" = betterproto2.field(11, betterproto2.TYPE_BOOL)
    requested_persistence: "ESessionPersistence" = betterproto2.field(
        12, betterproto2.TYPE_ENUM, default_factory=lambda: ESessionPersistence(0)
    )
    device_trust: "int" = betterproto2.field(13, betterproto2.TYPE_INT32)
    app_type: "EAuthTokenAppType" = betterproto2.field(
        14, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenAppType(0)
    )


@dataclass(eq=False, repr=False)
class CAuthenticationGetAuthSessionsForAccountResponse(betterproto2.Message):
    """
    message CAuthentication_GetAuthSessionsForAccount_Request {}
    """

    client_ids: "list[int]" = betterproto2.field(1, betterproto2.TYPE_UINT64, repeated=True)


@dataclass(eq=False, repr=False)
class CAuthenticationGetPasswordRsaPublicKeyRequest(betterproto2.Message):
    account_name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CAuthenticationGetPasswordRsaPublicKeyResponse(betterproto2.Message):
    publickey_mod: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    publickey_exp: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    timestamp: "int" = betterproto2.field(3, betterproto2.TYPE_UINT64)


@dataclass(eq=False, repr=False)
class CAuthenticationPollAuthSessionStatusRequest(betterproto2.Message):
    client_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    request_id: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)
    token_to_revoke: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)


@dataclass(eq=False, repr=False)
class CAuthenticationPollAuthSessionStatusResponse(betterproto2.Message):
    new_client_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    new_challenge_url: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    refresh_token: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    access_token: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    had_remote_interaction: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)
    account_name: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)
    new_guard_data: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    agreement_session_url: "str" = betterproto2.field(8, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CAuthenticationRefreshTokenEnumerateRequest(betterproto2.Message):
    include_revoked: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)


@dataclass(eq=False, repr=False)
class CAuthenticationRefreshTokenEnumerateResponse(betterproto2.Message):
    refresh_tokens: "list[CAuthenticationRefreshTokenEnumerateResponseRefreshTokenDescription]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )
    requesting_token: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)


@dataclass(eq=False, repr=False)
class CAuthenticationRefreshTokenEnumerateResponseRefreshTokenDescription(betterproto2.Message):
    token_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    token_description: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    time_updated: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)
    platform_type: "EAuthTokenPlatformType" = betterproto2.field(
        4, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenPlatformType(0)
    )
    logged_in: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)
    os_platform: "int" = betterproto2.field(6, betterproto2.TYPE_UINT32)
    auth_type: "int" = betterproto2.field(7, betterproto2.TYPE_UINT32)
    gaming_device_type: "int" = betterproto2.field(8, betterproto2.TYPE_UINT32)
    first_seen: "CAuthenticationRefreshTokenEnumerateResponseTokenUsageEvent | None" = betterproto2.field(
        9, betterproto2.TYPE_MESSAGE, optional=True
    )
    last_seen: "CAuthenticationRefreshTokenEnumerateResponseTokenUsageEvent | None" = betterproto2.field(
        10, betterproto2.TYPE_MESSAGE, optional=True
    )
    os_type: "int" = betterproto2.field(11, betterproto2.TYPE_INT32)
    authentication_type: "EAuthenticationType" = betterproto2.field(
        12, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthenticationType(0)
    )
    effective_token_state: "EAuthTokenState" = betterproto2.field(
        13, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenState(0)
    )


@dataclass(eq=False, repr=False)
class CAuthenticationRefreshTokenEnumerateResponseTokenUsageEvent(betterproto2.Message):
    time: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    ip: "CMsgIpAddress | None" = betterproto2.field(2, betterproto2.TYPE_MESSAGE, optional=True)
    locale: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    country: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    state: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)
    city: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CAuthenticationRefreshTokenRevokeRequest(betterproto2.Message):
    """
    message CAuthentication_Token_Revoke_Response {}
    """

    token_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    steamid: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    revoke_action: "EAuthTokenRevokeAction" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenRevokeAction(0)
    )
    signature: "bytes" = betterproto2.field(4, betterproto2.TYPE_BYTES)


@dataclass(eq=False, repr=False)
class CAuthenticationTokenRevokeRequest(betterproto2.Message):
    token: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    revoke_action: "EAuthTokenRevokeAction" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthTokenRevokeAction(0)
    )


@dataclass(eq=False, repr=False)
class CAuthenticationUpdateAuthSessionWithMobileConfirmationRequest(betterproto2.Message):
    version: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)
    client_id: "int" = betterproto2.field(2, betterproto2.TYPE_UINT64)
    steamid: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)
    signature: "bytes" = betterproto2.field(4, betterproto2.TYPE_BYTES)
    confirm: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)
    persistence: "ESessionPersistence" = betterproto2.field(
        6, betterproto2.TYPE_ENUM, default_factory=lambda: ESessionPersistence(0)
    )


@dataclass(eq=False, repr=False)
class CAuthenticationUpdateAuthSessionWithSteamGuardCodeRequest(betterproto2.Message):
    client_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    steamid: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    code: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    code_type: "EAuthSessionGuardType" = betterproto2.field(
        4, betterproto2.TYPE_ENUM, default_factory=lambda: EAuthSessionGuardType(0)
    )


@dataclass(eq=False, repr=False)
class CAuthenticationUpdateAuthSessionWithSteamGuardCodeResponse(betterproto2.Message):
    agreement_session_url: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CMsgIpAddress(betterproto2.Message):
    """


    Oneofs:
        - ip:
    """

    v4: "int | None" = betterproto2.field(1, betterproto2.TYPE_FIXED32, optional=True, group="ip")
    v6: "bytes | None" = betterproto2.field(2, betterproto2.TYPE_BYTES, optional=True, group="ip")


@dataclass(eq=False, repr=False)
class CPhoneAccountPhoneStatusResponse(betterproto2.Message):
    """
    message CPhone_VerifyAccountPhoneWithCode_Response {}

    self written
    """

    verified_phone: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    can_add_two_factor_phone: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)


@dataclass(eq=False, repr=False)
class CPhoneAddPhoneToAccountResponse(betterproto2.Message):
    success: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    phone_number_type: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False)
class CPhoneConfirmAddPhoneToAccountRequest(betterproto2.Message):
    steamid: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    stoken: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CPhoneIsAccountWaitingForEmailConfirmationResponse(betterproto2.Message):
    """
    message CPhone_IsAccountWaitingForEmailConfirmation_Request {}
    """

    awaiting_email_confirmation: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    seconds_to_wait: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class CPhoneSendPhoneVerificationCodeRequest(betterproto2.Message):
    language: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class CPhoneSetAccountPhoneNumberRequest(betterproto2.Message):
    """
    message CPhone_SendPhoneVerificationCode_Response {}
    """

    phone_number: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    phone_country_code: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CPhoneSetAccountPhoneNumberResponse(betterproto2.Message):
    confirmation_email_address: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    phone_number_formatted: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CPhoneVerifyAccountPhoneWithCodeRequest(betterproto2.Message):
    code: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CRemoveAuthenticatorViaChallengeContinueReplacementToken(betterproto2.Message):
    shared_secret: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)
    serial_number: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    revocation_code: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    uri: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    server_time: "int" = betterproto2.field(5, betterproto2.TYPE_UINT64)
    account_name: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)
    token_gid: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    identity_secret: "bytes" = betterproto2.field(8, betterproto2.TYPE_BYTES)
    secret_1: "bytes" = betterproto2.field(9, betterproto2.TYPE_BYTES)
    status: "int" = betterproto2.field(10, betterproto2.TYPE_INT32)
    steamguard_scheme: "int" = betterproto2.field(11, betterproto2.TYPE_UINT32)
    steamid: "int" = betterproto2.field(12, betterproto2.TYPE_FIXED64)


@dataclass(eq=False, repr=False)
class CTwoFactorAddAuthenticatorRequest(betterproto2.Message):
    steamid: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    authenticator_time: "int" = betterproto2.field(2, betterproto2.TYPE_UINT64)
    serial_number: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)
    authenticator_type: "int" = betterproto2.field(4, betterproto2.TYPE_UINT32)
    device_identifier: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)
    http_headers: "list[str]" = betterproto2.field(7, betterproto2.TYPE_STRING, repeated=True)
    version: "int" = betterproto2.field(8, betterproto2.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class CTwoFactorAddAuthenticatorResponse(betterproto2.Message):
    shared_secret: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)
    serial_number: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    revocation_code: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    uri: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    server_time: "int" = betterproto2.field(5, betterproto2.TYPE_UINT64)
    account_name: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)
    token_gid: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    identity_secret: "bytes" = betterproto2.field(8, betterproto2.TYPE_BYTES)
    secret_1: "bytes" = betterproto2.field(9, betterproto2.TYPE_BYTES)
    status: "int" = betterproto2.field(10, betterproto2.TYPE_INT32)
    phone_number_hint: "str" = betterproto2.field(11, betterproto2.TYPE_STRING)
    confirm_type: "int" = betterproto2.field(12, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False)
class CTwoFactorFinalizeAddAuthenticatorRequest(betterproto2.Message):
    steamid: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    authenticator_code: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    authenticator_time: "int" = betterproto2.field(3, betterproto2.TYPE_UINT64)
    activation_code: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    http_headers: "list[str]" = betterproto2.field(5, betterproto2.TYPE_STRING, repeated=True)
    validate_sms_code: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)


@dataclass(eq=False, repr=False)
class CTwoFactorFinalizeAddAuthenticatorResponse(betterproto2.Message):
    success: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    server_time: "int" = betterproto2.field(3, betterproto2.TYPE_UINT64)
    status: "int" = betterproto2.field(4, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False)
class CTwoFactorRemoveAuthenticatorRequest(betterproto2.Message):
    revocation_code: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    revocation_reason: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)
    steamguard_scheme: "int" = betterproto2.field(6, betterproto2.TYPE_UINT32)
    remove_all_steamguard_cookies: "bool" = betterproto2.field(7, betterproto2.TYPE_BOOL)


@dataclass(eq=False, repr=False)
class CTwoFactorRemoveAuthenticatorResponse(betterproto2.Message):
    success: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    server_time: "int" = betterproto2.field(3, betterproto2.TYPE_UINT64)
    revocation_attempts_remaining: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest(betterproto2.Message):
    sms_code: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    generate_new_token: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)
    version: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse(betterproto2.Message):
    success: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    replacement_token: "CRemoveAuthenticatorViaChallengeContinueReplacementToken | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


@dataclass(eq=False, repr=False)
class CTwoFactorRemoveAuthenticatorViaChallengeStartResponse(betterproto2.Message):
    """
    message CTwoFactor_RemoveAuthenticatorViaChallengeStart_Request {}
    """

    success: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)


@dataclass(eq=False, repr=False)
class CTwoFactorStatusRequest(betterproto2.Message):
    steamid: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    include: "ETwoFactorStatusFieldFlag" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: ETwoFactorStatusFieldFlag(0)
    )


@dataclass(eq=False, repr=False)
class CTwoFactorStatusResponse(betterproto2.Message):
    state: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    inactivation_reason: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)
    authenticator_type: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)
    authenticator_allowed: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)
    steamguard_scheme: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)
    token_gid: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)
    email_validated: "bool" = betterproto2.field(7, betterproto2.TYPE_BOOL)
    device_identifier: "str" = betterproto2.field(8, betterproto2.TYPE_STRING)
    time_created: "int" = betterproto2.field(9, betterproto2.TYPE_UINT32)
    revocation_attempts_remaining: "int" = betterproto2.field(10, betterproto2.TYPE_UINT32)
    classified_agent: "str" = betterproto2.field(11, betterproto2.TYPE_STRING)
    allow_external_authenticator: "bool" = betterproto2.field(12, betterproto2.TYPE_BOOL)
    time_transferred: "int" = betterproto2.field(13, betterproto2.TYPE_UINT32)
    version: "int" = betterproto2.field(14, betterproto2.TYPE_UINT32)
    last_seen_auth_token_id: "int" = betterproto2.field(15, betterproto2.TYPE_FIXED64)
    usages: "list[CTwoFactorUsageEvent]" = betterproto2.field(16, betterproto2.TYPE_MESSAGE, repeated=True)


@dataclass(eq=False, repr=False)
class CTwoFactorTimeRequest(betterproto2.Message):
    sender_time: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)


@dataclass(eq=False, repr=False)
class CTwoFactorTimeResponse(betterproto2.Message):
    server_time: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    skew_tolerance_seconds: "int" = betterproto2.field(2, betterproto2.TYPE_UINT64)
    large_time_jink: "int" = betterproto2.field(3, betterproto2.TYPE_UINT64)
    probe_frequency_seconds: "int" = betterproto2.field(4, betterproto2.TYPE_UINT32)
    adjusted_time_probe_frequency_seconds: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)
    hint_probe_frequency_seconds: "int" = betterproto2.field(6, betterproto2.TYPE_UINT32)
    sync_timeout: "int" = betterproto2.field(7, betterproto2.TYPE_UINT32)
    try_again_seconds: "int" = betterproto2.field(8, betterproto2.TYPE_UINT32)
    max_attempts: "int" = betterproto2.field(9, betterproto2.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class CTwoFactorUsageEvent(betterproto2.Message):
    time: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    usage_type: "ETwoFactorUsageType" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: ETwoFactorUsageType(0)
    )
    confirmation_type: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)
    confirmation_action: "int" = betterproto2.field(4, betterproto2.TYPE_INT32)
