# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protobufs/notification.proto
# plugin: python-betterproto2
# This file has been @generated

# Processed by generate_protos.py: removed 'message_pool', formatted.

__all__ = (
    "CSteamNotificationGetSteamNotificationsRequest",
    "CSteamNotificationGetSteamNotificationsResponse",
    "CSteamNotificationMarkNotificationsReadNotification",
    "CSteamNotificationMarkNotificationsViewedNotification",
    "ESteamNotificationType",
    "SteamNotificationData",
)
from dataclasses import dataclass

import betterproto2

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class ESteamNotificationType(betterproto2.Enum):
    k_ESteamNotificationType_Invalid = 0
    k_ESteamNotificationType_Test = 1
    k_ESteamNotificationType_Gift = 2
    k_ESteamNotificationType_Comment = 3
    k_ESteamNotificationType_Item = 4
    k_ESteamNotificationType_FriendInvite = 5
    k_ESteamNotificationType_MajorSale = 6
    k_ESteamNotificationType_PreloadAvailable = 7
    k_ESteamNotificationType_Wishlist = 8
    k_ESteamNotificationType_TradeOffer = 9
    k_ESteamNotificationType_General = 10
    k_ESteamNotificationType_HelpRequest = 11
    k_ESteamNotificationType_AsyncGame = 12
    k_ESteamNotificationType_ChatMsg = 13
    k_ESteamNotificationType_ModeratorMsg = 14
    k_ESteamNotificationType_ParentalFeatureAccessRequest = 15
    k_ESteamNotificationType_FamilyInvite = 16
    k_ESteamNotificationType_FamilyPurchaseRequest = 17
    k_ESteamNotificationType_ParentalPlaytimeRequest = 18
    k_ESteamNotificationType_FamilyPurchaseRequestResponse = 19
    k_ESteamNotificationType_ParentalFeatureAccessResponse = 20
    k_ESteamNotificationType_ParentalPlaytimeResponse = 21
    k_ESteamNotificationType_RequestedGameAdded = 22
    k_ESteamNotificationType_SendToPhone = 23
    k_ESteamNotificationType_ClipDownloaded = 24
    k_ESteamNotificationType_2FAPrompt = 25
    k_ESteamNotificationType_MobileConfirmation = 26
    k_ESteamNotificationType_PartnerEvent = 27
    k_ESteamNotificationType_PlaytestInvite = 28
    k_ESteamNotificationType_TradeReversal = 29
    k_ESteamNotificationType_ReportedContentAction = 30


@dataclass(eq=False, repr=False)
class CSteamNotificationGetSteamNotificationsRequest(betterproto2.Message):
    include_hidden: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    language: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)
    include_confirmation_count: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)
    include_pinned_counts: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)
    include_read: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)
    count_only: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)


@dataclass(eq=False, repr=False)
class CSteamNotificationGetSteamNotificationsResponse(betterproto2.Message):
    notifications: "list[SteamNotificationData]" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, repeated=True)
    confirmation_count: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)
    pending_gift_count: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)
    pending_friend_count: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)
    unread_count: "int" = betterproto2.field(6, betterproto2.TYPE_UINT32)
    pending_family_invite_count: "int" = betterproto2.field(7, betterproto2.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class CSteamNotificationMarkNotificationsReadNotification(betterproto2.Message):
    timestamp: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    notification_type: "ESteamNotificationType" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: ESteamNotificationType(0)
    )
    notification_ids: "list[int]" = betterproto2.field(3, betterproto2.TYPE_UINT64, repeated=True)
    mark_all_read: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)


@dataclass(eq=False, repr=False)
class CSteamNotificationMarkNotificationsViewedNotification(betterproto2.Message):
    remote_client_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    target_client_type: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class SteamNotificationData(betterproto2.Message):
    notification_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    notification_targets: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)
    notification_type: "ESteamNotificationType" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, default_factory=lambda: ESteamNotificationType(0)
    )
    body_data: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    read: "bool" = betterproto2.field(7, betterproto2.TYPE_BOOL)
    timestamp: "int" = betterproto2.field(8, betterproto2.TYPE_UINT32)
    hidden: "bool" = betterproto2.field(9, betterproto2.TYPE_BOOL)
    expiry: "int" = betterproto2.field(10, betterproto2.TYPE_UINT32)
    viewed: "int" = betterproto2.field(11, betterproto2.TYPE_UINT32)
