# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protobufs/phone.proto
# plugin: python-betterproto2
# This file has been @generated

# Processed by generate_protos.py: removed 'message_pool', formatted.

__all__ = (
    "CPhoneAccountPhoneStatusResponse",
    "CPhoneAddPhoneToAccountResponse",
    "CPhoneConfirmAddPhoneToAccountRequest",
    "CPhoneIsAccountWaitingForEmailConfirmationResponse",
    "CPhoneSendPhoneVerificationCodeRequest",
    "CPhoneSetAccountPhoneNumberRequest",
    "CPhoneSetAccountPhoneNumberResponse",
    "CPhoneVerifyAccountPhoneWithCodeRequest",
)
from dataclasses import dataclass

import betterproto2

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class CPhoneAccountPhoneStatusResponse(betterproto2.Message):
    """
    message CPhone_VerifyAccountPhoneWithCode_Response {}

    self written
    """

    verified_phone: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    can_add_two_factor_phone: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)


@dataclass(eq=False, repr=False)
class CPhoneAddPhoneToAccountResponse(betterproto2.Message):
    success: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    phone_number_type: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False)
class CPhoneConfirmAddPhoneToAccountRequest(betterproto2.Message):
    steamid: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    stoken: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CPhoneIsAccountWaitingForEmailConfirmationResponse(betterproto2.Message):
    """
    message CPhone_IsAccountWaitingForEmailConfirmation_Request {}
    """

    awaiting_email_confirmation: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    seconds_to_wait: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class CPhoneSendPhoneVerificationCodeRequest(betterproto2.Message):
    language: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class CPhoneSetAccountPhoneNumberRequest(betterproto2.Message):
    """
    message CPhone_SendPhoneVerificationCode_Response {}
    """

    phone_number: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    phone_country_code: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CPhoneSetAccountPhoneNumberResponse(betterproto2.Message):
    confirmation_email_address: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    phone_number_formatted: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


@dataclass(eq=False, repr=False)
class CPhoneVerifyAccountPhoneWithCodeRequest(betterproto2.Message):
    code: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
