# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protobufs/twofactor.proto
# plugin: python-betterproto2
# This file has been @generated

# Processed by generate_protos.py: removed 'message_pool', formatted.

__all__ = (
    "CRemoveAuthenticatorViaChallengeContinueReplacementToken",
    "CTwoFactorAddAuthenticatorRequest",
    "CTwoFactorAddAuthenticatorResponse",
    "CTwoFactorFinalizeAddAuthenticatorRequest",
    "CTwoFactorFinalizeAddAuthenticatorResponse",
    "CTwoFactorRemoveAuthenticatorRequest",
    "CTwoFactorRemoveAuthenticatorResponse",
    "CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest",
    "CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse",
    "CTwoFactorRemoveAuthenticatorViaChallengeStartResponse",
    "CTwoFactorStatusRequest",
    "CTwoFactorStatusResponse",
    "CTwoFactorTimeRequest",
    "CTwoFactorTimeResponse",
    "CTwoFactorUsageEvent",
    "ETwoFactorStatusFieldFlag",
    "ETwoFactorUsageType",
)
from dataclasses import dataclass

import betterproto2

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class ETwoFactorStatusFieldFlag(betterproto2.Enum):
    k_ETwoFactorStatusFieldFlag_None = 0
    k_ETwoFactorStatusFieldFlag_LastUsage = 1


class ETwoFactorUsageType(betterproto2.Enum):
    k_ETwoFactorUsageType_Unknown = 0
    k_ETwoFactorUsageType_None = 1
    k_ETwoFactorUsageType_MobileConfirmation = 2
    k_ETwoFactorUsageType_Login = 3


@dataclass(eq=False, repr=False)
class CRemoveAuthenticatorViaChallengeContinueReplacementToken(betterproto2.Message):
    shared_secret: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)
    serial_number: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    revocation_code: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    uri: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    server_time: "int" = betterproto2.field(5, betterproto2.TYPE_UINT64)
    account_name: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)
    token_gid: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    identity_secret: "bytes" = betterproto2.field(8, betterproto2.TYPE_BYTES)
    secret_1: "bytes" = betterproto2.field(9, betterproto2.TYPE_BYTES)
    status: "int" = betterproto2.field(10, betterproto2.TYPE_INT32)
    steamguard_scheme: "int" = betterproto2.field(11, betterproto2.TYPE_UINT32)
    steamid: "int" = betterproto2.field(12, betterproto2.TYPE_FIXED64)


@dataclass(eq=False, repr=False)
class CTwoFactorAddAuthenticatorRequest(betterproto2.Message):
    steamid: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    authenticator_time: "int" = betterproto2.field(2, betterproto2.TYPE_UINT64)
    serial_number: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)
    authenticator_type: "int" = betterproto2.field(4, betterproto2.TYPE_UINT32)
    device_identifier: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)
    http_headers: "list[str]" = betterproto2.field(7, betterproto2.TYPE_STRING, repeated=True)
    version: "int" = betterproto2.field(8, betterproto2.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class CTwoFactorAddAuthenticatorResponse(betterproto2.Message):
    shared_secret: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)
    serial_number: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    revocation_code: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    uri: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    server_time: "int" = betterproto2.field(5, betterproto2.TYPE_UINT64)
    account_name: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)
    token_gid: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    identity_secret: "bytes" = betterproto2.field(8, betterproto2.TYPE_BYTES)
    secret_1: "bytes" = betterproto2.field(9, betterproto2.TYPE_BYTES)
    status: "int" = betterproto2.field(10, betterproto2.TYPE_INT32)
    phone_number_hint: "str" = betterproto2.field(11, betterproto2.TYPE_STRING)
    confirm_type: "int" = betterproto2.field(12, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False)
class CTwoFactorFinalizeAddAuthenticatorRequest(betterproto2.Message):
    steamid: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    authenticator_code: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    authenticator_time: "int" = betterproto2.field(3, betterproto2.TYPE_UINT64)
    activation_code: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    http_headers: "list[str]" = betterproto2.field(5, betterproto2.TYPE_STRING, repeated=True)
    validate_sms_code: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)


@dataclass(eq=False, repr=False)
class CTwoFactorFinalizeAddAuthenticatorResponse(betterproto2.Message):
    success: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    server_time: "int" = betterproto2.field(3, betterproto2.TYPE_UINT64)
    status: "int" = betterproto2.field(4, betterproto2.TYPE_INT32)


@dataclass(eq=False, repr=False)
class CTwoFactorRemoveAuthenticatorRequest(betterproto2.Message):
    revocation_code: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    revocation_reason: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)
    steamguard_scheme: "int" = betterproto2.field(6, betterproto2.TYPE_UINT32)
    remove_all_steamguard_cookies: "bool" = betterproto2.field(7, betterproto2.TYPE_BOOL)


@dataclass(eq=False, repr=False)
class CTwoFactorRemoveAuthenticatorResponse(betterproto2.Message):
    success: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    server_time: "int" = betterproto2.field(3, betterproto2.TYPE_UINT64)
    revocation_attempts_remaining: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class CTwoFactorRemoveAuthenticatorViaChallengeContinueRequest(betterproto2.Message):
    sms_code: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    generate_new_token: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)
    version: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class CTwoFactorRemoveAuthenticatorViaChallengeContinueResponse(betterproto2.Message):
    success: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    replacement_token: "CRemoveAuthenticatorViaChallengeContinueReplacementToken | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


@dataclass(eq=False, repr=False)
class CTwoFactorRemoveAuthenticatorViaChallengeStartResponse(betterproto2.Message):
    """
    message CTwoFactor_RemoveAuthenticatorViaChallengeStart_Request {}
    """

    success: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)


@dataclass(eq=False, repr=False)
class CTwoFactorStatusRequest(betterproto2.Message):
    steamid: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    include: "ETwoFactorStatusFieldFlag" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: ETwoFactorStatusFieldFlag(0)
    )


@dataclass(eq=False, repr=False)
class CTwoFactorStatusResponse(betterproto2.Message):
    state: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    inactivation_reason: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)
    authenticator_type: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)
    authenticator_allowed: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)
    steamguard_scheme: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)
    token_gid: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)
    email_validated: "bool" = betterproto2.field(7, betterproto2.TYPE_BOOL)
    device_identifier: "str" = betterproto2.field(8, betterproto2.TYPE_STRING)
    time_created: "int" = betterproto2.field(9, betterproto2.TYPE_UINT32)
    revocation_attempts_remaining: "int" = betterproto2.field(10, betterproto2.TYPE_UINT32)
    classified_agent: "str" = betterproto2.field(11, betterproto2.TYPE_STRING)
    allow_external_authenticator: "bool" = betterproto2.field(12, betterproto2.TYPE_BOOL)
    time_transferred: "int" = betterproto2.field(13, betterproto2.TYPE_UINT32)
    version: "int" = betterproto2.field(14, betterproto2.TYPE_UINT32)
    last_seen_auth_token_id: "int" = betterproto2.field(15, betterproto2.TYPE_FIXED64)
    usages: "list[CTwoFactorUsageEvent]" = betterproto2.field(16, betterproto2.TYPE_MESSAGE, repeated=True)


@dataclass(eq=False, repr=False)
class CTwoFactorTimeRequest(betterproto2.Message):
    sender_time: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)


@dataclass(eq=False, repr=False)
class CTwoFactorTimeResponse(betterproto2.Message):
    server_time: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    skew_tolerance_seconds: "int" = betterproto2.field(2, betterproto2.TYPE_UINT64)
    large_time_jink: "int" = betterproto2.field(3, betterproto2.TYPE_UINT64)
    probe_frequency_seconds: "int" = betterproto2.field(4, betterproto2.TYPE_UINT32)
    adjusted_time_probe_frequency_seconds: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)
    hint_probe_frequency_seconds: "int" = betterproto2.field(6, betterproto2.TYPE_UINT32)
    sync_timeout: "int" = betterproto2.field(7, betterproto2.TYPE_UINT32)
    try_again_seconds: "int" = betterproto2.field(8, betterproto2.TYPE_UINT32)
    max_attempts: "int" = betterproto2.field(9, betterproto2.TYPE_UINT32)


@dataclass(eq=False, repr=False)
class CTwoFactorUsageEvent(betterproto2.Message):
    time: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    usage_type: "ETwoFactorUsageType" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: ETwoFactorUsageType(0)
    )
    confirmation_type: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)
    confirmation_action: "int" = betterproto2.field(4, betterproto2.TYPE_INT32)
